#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
from bpy.props import StringProperty

from . import constants as const


class TP3D_AddonPreferences(bpy.types.AddonPreferences):
    bl_idname = __package__

    default_export_folder: StringProperty(
        name="Default Export Folder",
        description="Default folder used when exporting STL / OBJ / 3MF files",
        default="",
        subtype='DIR_PATH',
    )  # type: ignore

    openTopographyApiKey: StringProperty(
        name="OpenTopography API Key",
        description="API key from portal.opentopography.org — free registration required for most datasets",
        default="",
    )  # type: ignore

    dismissed_update_version: StringProperty(
        name="Dismissed Update Version",
        description="Latest update version the user closed the notice for — re-shown once a newer version is found",
        default="",
    )  # type: ignore

    def draw(self, context):
        from . import temp
        layout = self.layout

        # Premium status
        if temp.PREMIUMVERSION:
            box = layout.box()
            row = box.row()
            row.label(text="Premium Version", icon='CHECKMARK')
            layout.separator()

        # OpenTopography API Key
        layout.label(text="OpenTopography API Key:", icon='INTERNET')
        layout.prop(self, "openTopographyApiKey", text="")
        if not self.openTopographyApiKey:
            layout.label(text="Required for most datasets — free at portal.opentopography.org", icon='ERROR')

        layout.separator()

        # Export
        layout.label(text="Export Settings:", icon='EXPORT')
        layout.prop(self, "default_export_folder")

        layout.separator()

        # Updates
        from . import updater
        layout.label(text="Updates:", icon='FILE_REFRESH')
        box = layout.box()
        current_str = ".".join(str(x) for x in const.ADDON_VERSION)

        if temp.PREMIUMVERSION:
            status = updater.premium_status
            latest_version = updater.premium_latest_version
            error_message = updater.premium_error_message
        else:
            status = updater.status
            latest_version = updater.latest_version
            error_message = updater.error_message

        if status == "idle":
            row = box.row(align=True)
            row.label(text=f"Current version: v{current_str}", icon='INFO')
            row.operator("tp3d.check_update", text="Check for Updates", icon='FILE_REFRESH')

        elif status == "checking":
            box.label(text="Checking for updates...", icon='TIME')

        elif status == "up_to_date":
            latest_str = ".".join(str(x) for x in latest_version)
            row = box.row(align=True)
            row.label(text=f"Up to date  (v{latest_str})", icon='CHECKMARK')
            row.operator("tp3d.check_update", text="", icon='FILE_REFRESH')

        elif status == "update_available":
            latest_str = ".".join(str(x) for x in latest_version)
            if self.dismissed_update_version != latest_str:
                row = box.row(align=True)
                row.label(text=f"Update available: v{latest_str}  (current: v{current_str})", icon='ERROR')
                row.operator("tp3d.check_update", text="", icon='FILE_REFRESH')
                row.operator("tp3d.dismiss_update", text="", icon='X').version = latest_str
                col = box.column()
                col.scale_y = 1.3
                if temp.PREMIUMVERSION:
                    col.operator("tp3d.open_premium_update", text=f"Get v{latest_str} on Patreon", icon='URL')
                else:
                    col.operator("tp3d.install_update", text=f"Download & Install v{latest_str}", icon='IMPORT')
                    box.label(text="Blender must be restarted after installing.", icon='INFO')
            else:
                row = box.row(align=True)
                row.label(text=f"Current version: v{current_str}", icon='INFO')
                row.operator("tp3d.check_update", text="Check for Updates", icon='FILE_REFRESH')

        elif status == "error":
            row = box.row(align=True)
            msg = error_message[:60] + ("..." if len(error_message) > 60 else "")
            row.label(text=f"Check failed: {msg}", icon='CANCEL')
            row.operator("tp3d.check_update", text="Retry", icon='FILE_REFRESH')

        layout.separator()


def get_prefs():
    """Convenience helper — returns the AddonPreferences instance."""
    return bpy.context.preferences.addons[__package__].preferences
