#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

import bpy
from bpy.props import BoolProperty, IntProperty, StringProperty

from . import constants as const

# OSM map-size limits: preference attribute -> constants.py name. Order here
# is the draw order in the preferences window.
OSM_SIZE_LIMITS = {
    "osm_limit_forest": "FOREST_MAXSIZE",
    "osm_limit_water": "WATER_MAXSIZE",
    "osm_limit_small_rivers": "SMALL_RIVERS_MAXSIZE",
    "osm_limit_scree": "SCREE_MAXSIZE",
    "osm_limit_city": "CITY_MAXSIZE",
    "osm_limit_greenspace": "GREENSPACE_MAXSIZE",
    "osm_limit_farmland": "FARMLAND_MAXSIZE",
    "osm_limit_glacier": "GLACIER_MAXSIZE",
    "osm_limit_buildings": "BUILDINGS_MAXSIZE",
    "osm_limit_roads": "ROADS_MAXSIZE",
    "osm_limit_streets": "STREETS_PRIMARY_THRESHOLD",
    "osm_limit_coastline": "COASTLINE_MAXSIZE",
    "osm_limit_coastline_waterpoly": "COASTLINE_WATERPOLY_MAXSIZE",
}


def sync_osm_size_limits(prefs):
    """Push the preference values into constants.py's OSM size limits.
    Called from register() and from every limit property's update callback."""
    for attr, const_name in OSM_SIZE_LIMITS.items():
        const.set_osm_size_limit(const_name, getattr(prefs, attr))


def _on_osm_limit_update(self, context):
    sync_osm_size_limits(self)


def _osm_limit_prop(const_name, name, description):
    default = const.OSM_SIZE_LIMIT_DEFAULTS[const_name]
    return IntProperty(
        name=name,
        description=description + " (km)",
        default=default,
        min=1,
        soft_max=max(1000, default * 2),
        update=_on_osm_limit_update,
    )


class TP3D_AddonPreferences(bpy.types.AddonPreferences):
    bl_idname = __package__

    show_osm_size_limits: BoolProperty(
        name="Show OSM Map Size Limits",
        default=False,
    )  # type: ignore

    osm_limit_forest: _osm_limit_prop(
        "FOREST_MAXSIZE", "Forest", "Forests are skipped above this map size"
    )  # type: ignore
    osm_limit_water: _osm_limit_prop(
        "WATER_MAXSIZE", "Water", "Water bodies and big rivers are skipped above this map size"
    )  # type: ignore
    osm_limit_small_rivers: _osm_limit_prop(
        "SMALL_RIVERS_MAXSIZE", "Small Rivers", "Small/minor waterways are skipped above this map size"
    )  # type: ignore
    osm_limit_scree: _osm_limit_prop(
        "SCREE_MAXSIZE", "Scree", "Scree is skipped above this map size"
    )  # type: ignore
    osm_limit_city: _osm_limit_prop(
        "CITY_MAXSIZE", "City", "City boundaries are skipped above this map size"
    )  # type: ignore
    osm_limit_greenspace: _osm_limit_prop(
        "GREENSPACE_MAXSIZE", "Greenspace", "Greenspaces are skipped above this map size"
    )  # type: ignore
    osm_limit_farmland: _osm_limit_prop(
        "FARMLAND_MAXSIZE", "Farmland", "Farmland is skipped above this map size"
    )  # type: ignore
    osm_limit_glacier: _osm_limit_prop(
        "GLACIER_MAXSIZE", "Glacier", "Glaciers are skipped above this map size"
    )  # type: ignore
    osm_limit_buildings: _osm_limit_prop(
        "BUILDINGS_MAXSIZE", "Buildings", "Buildings are skipped above this map size"
    )  # type: ignore
    osm_limit_roads: _osm_limit_prop(
        "ROADS_MAXSIZE", "Roads", "All roads are skipped above this map size"
    )  # type: ignore
    osm_limit_streets: _osm_limit_prop(
        "STREETS_PRIMARY_THRESHOLD",
        "Dense Streets",
        "Residential/service/footway/cycle/path roads are skipped above this map size",
    )  # type: ignore
    osm_limit_coastline: _osm_limit_prop(
        "COASTLINE_MAXSIZE",
        "Coastline (Overpass)",
        "Above this map size the ocean is built from the global water-polygon dataset instead of Overpass",
    )  # type: ignore
    osm_limit_coastline_waterpoly: _osm_limit_prop(
        "COASTLINE_WATERPOLY_MAXSIZE",
        "Coastline (Water Polygons)",
        "The ocean is skipped entirely above this map size",
    )  # type: ignore

    default_export_folder: StringProperty(
        name="Default Export Folder",
        description="Default folder used when exporting STL / OBJ / 3MF files",
        default="",
        subtype='DIR_PATH',
    )  # type: ignore

    openTopographyApiKey: StringProperty(
        name="OpenTopography API Key",
        description="API key from portal.opentopography.org — free registration required for most datasets",
        default="",
    )  # type: ignore

    dismissed_update_version: StringProperty(
        name="Dismissed Update Version",
        description="Latest update version the user closed the notice for — re-shown once a newer version is found",
        default="",
    )  # type: ignore

    def draw(self, context):
        from . import temp
        layout = self.layout

        # Premium status
        if temp.PREMIUMVERSION:
            box = layout.box()
            row = box.row()
            row.label(text="Premium Version", icon='CHECKMARK')
            layout.separator()

        # OpenTopography API Key
        layout.label(text="OpenTopography API Key:", icon='INTERNET')
        layout.prop(self, "openTopographyApiKey", text="")
        if not self.openTopographyApiKey:
            layout.label(text="Required for most datasets — free at portal.opentopography.org", icon='ERROR')

        layout.separator()

        # Export
        layout.label(text="Export Settings:", icon='EXPORT')
        layout.prop(self, "default_export_folder")

        layout.separator()

        # OSM map-size limits
        row = layout.row()
        row.prop(
            self,
            "show_osm_size_limits",
            text="OSM Map Size Limits (km):",
            icon='TRIA_DOWN' if self.show_osm_size_limits else 'TRIA_RIGHT',
            emboss=False,
        )
        if self.show_osm_size_limits:
            box = layout.box()
            box.label(text="OSM elements are skipped on maps larger than these sizes.", icon='INFO')
            box.label(text="Higher values mean larger Overpass downloads and slower generation.", icon='ERROR')
            grid = box.grid_flow(row_major=True, columns=2, even_columns=True, align=False)
            for attr in OSM_SIZE_LIMITS:
                grid.prop(self, attr)
            box.operator("tp3d.reset_osm_size_limits", icon='LOOP_BACK')

        layout.separator()

        # Updates
        from . import updater
        layout.label(text="Updates:", icon='FILE_REFRESH')
        box = layout.box()
        current_str = ".".join(str(x) for x in const.ADDON_VERSION)

        if temp.PREMIUMVERSION:
            status = updater.premium_status
            latest_version = updater.premium_latest_version
            error_message = updater.premium_error_message
        else:
            status = updater.status
            latest_version = updater.latest_version
            error_message = updater.error_message

        if status == "idle":
            row = box.row(align=True)
            row.label(text=f"Current version: v{current_str}", icon='INFO')
            row.operator("tp3d.check_update", text="Check for Updates", icon='FILE_REFRESH')

        elif status == "checking":
            box.label(text="Checking for updates...", icon='TIME')

        elif status == "up_to_date":
            latest_str = ".".join(str(x) for x in latest_version)
            row = box.row(align=True)
            row.label(text=f"Up to date  (v{latest_str})", icon='CHECKMARK')
            row.operator("tp3d.check_update", text="", icon='FILE_REFRESH')

        elif status == "update_available":
            latest_str = ".".join(str(x) for x in latest_version)
            if self.dismissed_update_version != latest_str:
                row = box.row(align=True)
                row.label(text=f"Update available: v{latest_str}  (current: v{current_str})", icon='ERROR')
                row.operator("tp3d.check_update", text="", icon='FILE_REFRESH')
                row.operator("tp3d.dismiss_update", text="", icon='X').version = latest_str
                col = box.column()
                col.scale_y = 1.3
                if temp.PREMIUMVERSION:
                    col.operator("tp3d.open_premium_update", text=f"Get v{latest_str} on Patreon", icon='URL')
                else:
                    col.operator("tp3d.install_update", text=f"Download & Install v{latest_str}", icon='IMPORT')
                    box.label(text="Blender must be restarted after installing.", icon='INFO')
            else:
                row = box.row(align=True)
                row.label(text=f"Current version: v{current_str}", icon='INFO')
                row.operator("tp3d.check_update", text="Check for Updates", icon='FILE_REFRESH')

        elif status == "error":
            row = box.row(align=True)
            msg = error_message[:60] + ("..." if len(error_message) > 60 else "")
            row.label(text=f"Check failed: {msg}", icon='CANCEL')
            row.operator("tp3d.check_update", text="Retry", icon='FILE_REFRESH')

        layout.separator()


def get_prefs():
    """Convenience helper — returns the AddonPreferences instance."""
    return bpy.context.preferences.addons[__package__].preferences
