#  Copyright (C) 2026  EmGi

# You are free to modify it under the terms of the GNU General Public License as published by the Free Software Foundation.
# You are free to use any models Generated by this Addon Commercially

"""Land-cover reference plane.

Fetches an ESA WorldCover land-cover classification crop for a lat/lon bbox
via Microsoft Planetary Computer's public STAC + Data API (no account/token
needed, CC-BY-4.0 license permits commercial reuse with attribution) and
places it in the scene as a flat, unlit reference plane aligned with the
generated terrain.

WorldCover is a real per-pixel classification (derived from Sentinel-1/2,
10m resolution) into a fixed set of categories -- unlike a true-color photo,
it needs no client-side color simplification: the Data API colorizes the
classification values server-side from a colormap we supply (_LANDCOVER_PALETTE
below, a more "natural" earth-tone set rather than WorldCover's own
high-contrast official legend), so the fetched PNG is already flat and clean.

A single STAC item only covers so much ground (~110km for a Sentinel-2 tile,
~200-300km for a WorldCover tile) -- larger requested areas are split into a
grid of sub-bbox "chunks" (mirroring the tiling _rg_start_osm_prefetch already
does for Overpass in generation.py), fetched in parallel, and stitched into
one image on the main thread.
"""

import concurrent.futures
import hashlib
import json
import math
import os
import time
from typing import NamedTuple

import numpy as np  # type: ignore
import requests
from mathutils import Vector  # type: ignore

from .. import constants as const
from .geo import convert_to_blender_coordinates
from .geometry2d import debug_collection
from .scene import remove_objects

_STAC_SEARCH_URL = "https://planetarycomputer.microsoft.com/api/stac/v1/search"
_DATA_API_BASE = "https://planetarycomputer.microsoft.com/api/data/v1"
_LANDCOVER_COLLECTION = "esa-worldcover"
_PHOTO_COLLECTION = "sentinel-2-l2a"
_MAX_PX = 1600  # overall stitched-image long-edge budget
_USER_AGENT = "TrailPrint3D_3.00"

# Physical chunk size (km) for the tiling grid -- comfortably under a single
# Sentinel-2 tile's ~110km footprint (the tighter of the two collections),
# so every chunk is guaranteed to land fully inside one source item.
_CHUNK_KM = 80
_KM_PER_DEGREE_LAT = 111.0

# ESA WorldCover ships as fixed 3x3 degree tiles named by their SW corner
# (e.g. "N45E006" = the cell from 45N,6E to 48N,9E). Snapping our own chunk
# grid to these lines means a chunk can never straddle a WorldCover tile
# boundary -- so there's always exactly one unambiguous right answer for
# which item covers it, instead of relying on the STAC search to guess well
# near an edge (best-overlap picking among a handful of candidates helps,
# per _stac_search, but isn't a guaranteed fix).
_WORLDCOVER_GRID_DEG = 3.0

SATELLITE_PLANE_NAME = "TP3D_SatelliteRef"
DEBUG_RAW_PLANE_NAME = "TP3D_SatelliteRef_DebugRaw"
DEBUG_COLLECTION_NAME = "TP3D_Debug_Satellite"

# Custom colormap (WorldCover class value -> RGBA 0-255) applied server-side
# via the Data API's `colormap` param, replacing WorldCover's own official
# legend (bright red Built-up, neon green Tree cover, etc.) with muted,
# "natural" earth tones.
_LANDCOVER_PALETTE = {
    10: [34, 85, 34, 255],     # Tree cover -> dark green
    20: [140, 125, 65, 255],   # Shrubland -> olive/tan
    30: [178, 165, 89, 255],   # Grassland -> tan-yellow
    40: [191, 173, 115, 255],  # Cropland -> wheat
    50: [89, 89, 89, 255],     # Built-up -> dark gray
    60: [153, 140, 115, 255],  # Bare/sparse vegetation -> light tan-gray
    70: [242, 242, 247, 255],  # Snow and ice -> white
    80: [38, 89, 153, 255],    # Permanent water bodies -> blue
    90: [64, 128, 128, 255],   # Herbaceous wetland -> teal
    95: [38, 115, 89, 255],    # Mangroves -> teal-green
    100: [166, 153, 115, 255], # Moss and lichen -> tan
}
# Fill color for a chunk/pixel with no WorldCover coverage (missing tile, or
# nodata within an otherwise-valid tile). WorldCover is a land-cover product
# -- it simply has no tiles at all over open ocean far from any coast, and
# masks deep water as nodata even within tiles that do have some coastline
# in them (confirmed: STAC search returns zero items for pure open-ocean
# bboxes). At the scale where this fallback actually triggers, "no
# coverage" is overwhelmingly open ocean, not a fetch error -- so it's
# colored the same blue as classified water instead of a neutral gray.
_FALLBACK_RGBA = tuple(c / 255.0 for c in _LANDCOVER_PALETTE[80])

LANDCOVER_IMAGE_NAME = "TP3D_LandCover"
PHOTO_IMAGE_NAME = "TP3D_Satellite_Photo"

# WorldCover class value -> the addon's own existing semantic material name
# (utils/primitives.py:setupColors()). Reused deliberately rather than
# inventing new materials: these are the same materials PAINT mode's
# OSM-element coloring already assigns (color_map_faces_by_terrain(), in
# terrain.py) and the ones the export/slicer pipeline maps to filament
# colors -- unlike the reference plane's own palette above, paint_terrain_
# from_landcover() colors real, exported/printed terrain faces.
_LANDCOVER_MATERIAL_MAP = {
    10: "FOREST",      # Tree cover
    20: "GREENSPACE",  # Shrubland
    30: "GREENSPACE",  # Grassland
    40: "FARMLAND",    # Cropland
    50: "CITY",        # Built-up
    60: "MOUNTAIN",    # Bare/sparse vegetation
    70: "GLACIER",     # Snow and ice
    80: "WATER",       # Permanent water bodies
    90: "WATER",       # Herbaceous wetland
    95: "FOREST",      # Mangroves
    100: "MOUNTAIN",   # Moss and lichen
}
# Max per-pixel RGB distance (0-255 scale) to accept a sample as a real
# palette match -- beyond this it's treated as unclassifiable (e.g. a
# no-data fallback-gray patch) and the face is left with whatever material
# it already had.
_LANDCOVER_MATCH_MAX_DIST = 30.0


class TiledCrop(NamedTuple):
    """Result of a (possibly multi-chunk) fetch -- consumed by _load_stitched_image()."""
    tiles: list        # list of dicts: {row, col, path (str|None), width, height}
    n_rows: int
    n_cols: int
    total_width: int
    total_height: int


def _bbox_overlap_area(a, b):
    """Overlap area (in degrees^2) between two [minx, miny, maxx, maxy] boxes."""
    ox = max(0.0, min(a[2], b[2]) - max(a[0], b[0]))
    oy = max(0.0, min(a[3], b[3]) - max(a[1], b[1]))
    return ox * oy


def _stac_search(collection, min_lat, max_lat, min_lon, max_lon, sortby=None, max_retries=3):
    """Query Planetary Computer's STAC API for the item that best covers bbox.

    Fetches a handful of candidates (limit=1 only guarantees *a* match, not
    the *best* one -- near a source tile's own boundary it can return a
    neighboring tile that only grazes the requested bbox at the edge,
    leaving it almost entirely nodata) and picks whichever candidate's own
    bbox overlaps our requested bbox the most.

    Returns the STAC item dict, or None if nothing suitable was found.
    """
    target = [min_lon, min_lat, max_lon, max_lat]
    payload = {
        "collections": [collection],
        "bbox": target,
        "limit": 6,
    }
    if sortby:
        payload["sortby"] = sortby
    for attempt in range(max_retries):
        try:
            response = requests.post(
                _STAC_SEARCH_URL, json=payload,
                headers={"User-Agent": _USER_AGENT}, timeout=30,
            )
            if response.status_code == 200:
                features = response.json().get("features", [])
                if not features:
                    return None
                return max(
                    features,
                    key=lambda feat: _bbox_overlap_area(target, feat.get("bbox", target)),
                )
            print(f"Satellite STAC search status {response.status_code}, retrying...")
        except requests.exceptions.Timeout:
            print(f"Satellite STAC search timed out (attempt {attempt + 1}/{max_retries})")
        except requests.RequestException as e:
            print(f"Satellite STAC search failed: {e}")
        time.sleep(3 + attempt)
    return None


def _render_crop(collection, item, asset, width, height, min_lat, max_lat, min_lon, max_lon,
                  out_path, colormap_name=None, colormap=None, max_retries=3):
    """Fetch a bbox-cropped, reprojected PNG (at the given pixel size) for a STAC item asset.

    Writes the PNG bytes to out_path. Returns True on success. The Data API
    crops/reprojects (and, when colormap_name/colormap is given, colorizes)
    server-side, so no raster library is needed locally.
    """
    feature = {
        "type": "Feature",
        "properties": {},
        "geometry": {
            "type": "Polygon",
            "coordinates": [[
                [min_lon, min_lat], [max_lon, min_lat],
                [max_lon, max_lat], [min_lon, max_lat],
                [min_lon, min_lat],
            ]],
        },
    }
    url = f"{_DATA_API_BASE}/item/feature/{width}x{height}.png"
    params = {
        "collection": item.get("collection", collection),
        "item": item["id"],
        "assets": asset,
    }
    if colormap_name:
        params["colormap_name"] = colormap_name
    if colormap:
        params["colormap"] = json.dumps(colormap)
    for attempt in range(max_retries):
        try:
            response = requests.post(
                url, params=params, json=feature,
                headers={"User-Agent": _USER_AGENT}, timeout=60,
            )
            if response.status_code == 200 and response.content:
                with open(out_path, "wb") as f:
                    f.write(response.content)
                return True
            print(f"Satellite crop status {response.status_code}, retrying...")
        except requests.exceptions.Timeout:
            print(f"Satellite crop timed out (attempt {attempt + 1}/{max_retries})")
        except requests.RequestException as e:
            print(f"Satellite crop failed: {e}")
        time.sleep(3 + attempt)
    return False


def _cache_key(prefix, min_lat, max_lat, min_lon, max_lon, variant=None):
    payload = {
        "bbox": [round(min_lat, 7), round(max_lat, 7), round(min_lon, 7), round(max_lon, 7)],
        "prefix": prefix,
        # Bump whenever fetch/selection logic changes (not just the palette)
        # so a fix like "pick the best-overlapping STAC item" actually takes
        # effect on regenerate instead of silently re-serving a cached PNG
        # that was fetched under the old, buggy selection logic.
        "fetch_logic_version": 3,
    }
    if variant is not None:
        # Included so a future palette edit busts the cache automatically,
        # instead of silently keeping serving old-colored cached PNGs.
        payload["variant"] = variant
    data = json.dumps(payload, sort_keys=True).encode("utf-8")
    return hashlib.sha256(data).hexdigest()


def _get_cached_crop(prefix, collection, asset, min_lat, max_lat, min_lon, max_lon,
                      disable_cache, max_cache_age_hours, width, height,
                      sortby=None, colormap_name=None, colormap=None):
    """Shared cache-then-fetch logic for one chunk of either the land-cover or photo crop."""
    os.makedirs(const.satellite_cache_dir, exist_ok=True)
    variant = json.dumps(colormap, sort_keys=True) if colormap else colormap_name
    cache_path = os.path.join(
        const.satellite_cache_dir,
        f"{_cache_key(prefix, min_lat, max_lat, min_lon, max_lon, variant=variant)}.png",
    )

    if os.path.exists(cache_path) and not disable_cache:
        age_hours = (time.time() - os.path.getmtime(cache_path)) / 3600
        if age_hours < max_cache_age_hours:
            print(f"Cached {prefix} chunk found")
            return cache_path

    item = _stac_search(collection, min_lat, max_lat, min_lon, max_lon, sortby=sortby)
    if item is None:
        print(f"No {collection} coverage found for this chunk")
        return None

    if not _render_crop(collection, item, asset, width, height, min_lat, max_lat, min_lon, max_lon,
                         cache_path, colormap_name=colormap_name, colormap=colormap):
        return None

    return cache_path


def _pixel_dims(lat_span, lon_span, max_px):
    """Aspect-preserving (width, height) for lat/lon spans, capped at max_px on the long edge."""
    if lon_span >= lat_span:
        return max_px, max(1, round(max_px * lat_span / lon_span))
    return max(1, round(max_px * lon_span / lat_span)), max_px


def _grid_breaks(min_v, max_v, step_deg, snap_deg=None):
    """Sorted breakpoints spanning [min_v, max_v]: roughly step_deg apart,
    plus (if snap_deg given) every exact multiple of snap_deg strictly
    inside the range, so no resulting interval straddles a snap_deg line.
    """
    span = max_v - min_v
    n = max(1, math.ceil(span / step_deg))
    breaks = {min_v, max_v}
    for i in range(1, n):
        breaks.add(min_v + i * (span / n))
    if snap_deg:
        v = math.ceil(min_v / snap_deg) * snap_deg
        while v < max_v - 1e-9:
            if v > min_v + 1e-9:
                breaks.add(v)
            v += snap_deg
    return sorted(breaks)


def _fetch_tiled(prefix, collection, asset, min_lat, max_lat, min_lon, max_lon,
                  disable_cache, max_cache_age_hours, sortby=None,
                  colormap_name=None, colormap=None, grid_snap_deg=None):
    """Fetch bbox as a grid of _CHUNK_KM-sized chunks (1x1 for anything smaller),
    each independently STAC-searched + cropped, in parallel.

    grid_snap_deg (e.g. _WORLDCOVER_GRID_DEG), if given, additionally splits
    the grid at every multiple of that many degrees, so a chunk can never
    straddle a known source-tile grid line -- rows/columns then have uneven
    spans, so each chunk carries its own pixel size and canvas offset rather
    than a single uniform chunk_w/chunk_h.

    Safe to call from a worker thread -- does no bpy.* work. Returns a
    TiledCrop, or None if every chunk failed (no coverage / all requests
    failed) -- callers must treat that as non-fatal.
    """
    lat_span = max_lat - min_lat
    lon_span = max_lon - min_lon
    if lat_span <= 0 or lon_span <= 0:
        return None

    center_lat = (min_lat + max_lat) / 2.0
    lat_step_deg = _CHUNK_KM / _KM_PER_DEGREE_LAT
    lon_step_deg = _CHUNK_KM / max(1e-6, _KM_PER_DEGREE_LAT * math.cos(math.radians(center_lat)))
    lat_breaks = _grid_breaks(min_lat, max_lat, lat_step_deg, snap_deg=grid_snap_deg)
    lon_breaks = _grid_breaks(min_lon, max_lon, lon_step_deg, snap_deg=grid_snap_deg)
    n_rows = len(lat_breaks) - 1
    n_cols = len(lon_breaks) - 1

    total_w, total_h = _pixel_dims(lat_span, lon_span, _MAX_PX)
    col_widths = [max(1, round(total_w * (lon_breaks[c + 1] - lon_breaks[c]) / lon_span))
                  for c in range(n_cols)]
    row_heights = [max(1, round(total_h * (lat_breaks[r + 1] - lat_breaks[r]) / lat_span))
                   for r in range(n_rows)]
    total_w = sum(col_widths)
    total_h = sum(row_heights)
    col_offsets = [sum(col_widths[:c]) for c in range(n_cols)]
    row_offsets = [sum(row_heights[:r]) for r in range(n_rows)]

    tasks = [
        {
            "row": row, "col": col,
            "min_lat": lat_breaks[row], "max_lat": lat_breaks[row + 1],
            "min_lon": lon_breaks[col], "max_lon": lon_breaks[col + 1],
            "width": col_widths[col], "height": row_heights[row],
            "x0": col_offsets[col], "y0": row_offsets[row],
        }
        for row in range(n_rows) for col in range(n_cols)
    ]

    def _fetch_one(t):
        t["path"] = _get_cached_crop(
            prefix, collection, asset,
            t["min_lat"], t["max_lat"], t["min_lon"], t["max_lon"],
            disable_cache, max_cache_age_hours, t["width"], t["height"],
            sortby=sortby, colormap_name=colormap_name, colormap=colormap,
        )
        return t

    if len(tasks) == 1:
        results = [_fetch_one(tasks[0])]
    else:
        print(f"Satellite {prefix}: area exceeds one source tile, fetching {n_rows}x{n_cols} chunks")
        with concurrent.futures.ThreadPoolExecutor(max_workers=min(6, len(tasks))) as ex:
            results = list(ex.map(_fetch_one, tasks))

    if not any(t["path"] for t in results):
        return None

    return TiledCrop(tiles=results, n_rows=n_rows, n_cols=n_cols,
                      total_width=total_w, total_height=total_h)


def get_cached_landcover_image(min_lat, max_lat, min_lon, max_lon,
                                disable_cache=False, max_cache_age_hours=720):
    """Return a TiledCrop for an ESA WorldCover land-cover map of bbox.

    Disk-cached per chunk (same convention as the Overpass cache). Safe to
    call from a worker thread -- does no bpy.* work. Returns None if no
    coverage could be found/fetched anywhere in bbox; callers must treat
    that as non-fatal. The classification is colorized server-side with our
    own _LANDCOVER_PALETTE -- no client-side color processing needed.
    """
    return _fetch_tiled(
        "landcover", _LANDCOVER_COLLECTION, "map",
        min_lat, max_lat, min_lon, max_lon, disable_cache, max_cache_age_hours,
        colormap=_LANDCOVER_PALETTE, grid_snap_deg=_WORLDCOVER_GRID_DEG,
    )


def get_cached_photo_image(min_lat, max_lat, min_lon, max_lon,
                            disable_cache=False, max_cache_age_hours=720):
    """Return a TiledCrop for a true-color Sentinel-2 photo of bbox.

    Debug-only companion to get_cached_landcover_image() -- lets the WorldCover
    classification be checked against the real photo it was derived from.
    Same caching/threading/tiling contract as get_cached_landcover_image().
    """
    return _fetch_tiled(
        "photo", _PHOTO_COLLECTION, "visual",
        min_lat, max_lat, min_lon, max_lon, disable_cache, max_cache_age_hours,
        sortby=[{"field": "eo:cloud_cover", "direction": "asc"}],
    )


def _load_stitched_image(name, tiled):
    """Load a (possibly multi-chunk) TiledCrop into a single named Blender image.

    Main-thread only. Always builds through a fallback-gray canvas and
    alpha-composites each chunk onto it, even for a single chunk: a source
    tile's own footprint rarely lines up exactly with our axis-aligned bbox
    (Sentinel-2 tiles in particular are UTM-rotated squares), so *any* crop
    can have a nodata (alpha=0) corner/edge, not just a fully-missing chunk.
    Compositing on alpha means those read as neutral gray instead of a black
    hole, and a chunk that failed to fetch entirely is just left at fallback.
    """
    import bpy  # type: ignore

    stale = bpy.data.images.get(name)
    if stale is not None:
        bpy.data.images.remove(stale)

    if not any(t["path"] for t in tiled.tiles):
        return None

    canvas = np.empty((tiled.total_height, tiled.total_width, 4), dtype=np.float32)
    canvas[..., :] = _FALLBACK_RGBA

    for t in tiled.tiles:
        if not t["path"]:
            continue
        chunk_img = bpy.data.images.load(t["path"])
        cw, ch = chunk_img.size
        buf = np.empty(cw * ch * 4, dtype=np.float32)
        chunk_img.pixels.foreach_get(buf)
        chunk_pixels = buf.reshape(ch, cw, 4)
        bpy.data.images.remove(chunk_img)

        y0 = t["y0"]
        x0 = t["x0"]
        h = min(ch, t["height"], tiled.total_height - y0)
        w = min(cw, t["width"], tiled.total_width - x0)
        if h > 0 and w > 0:
            chunk_slice = chunk_pixels[:h, :w, :]
            valid = chunk_slice[..., 3] > 0.5
            canvas_slice = canvas[y0:y0 + h, x0:x0 + w, :]
            canvas_slice[valid] = chunk_slice[valid]

    img = bpy.data.images.new(name, tiled.total_width, tiled.total_height, alpha=True)
    img.pixels.foreach_set(canvas.reshape(-1))
    img.update()
    return img


def _build_reference_plane(name, image, corners, x_shift, z_height, tp3d, collection, material_name):
    """Build (replacing any prior object of the same name) a flat unlit
    image plane from 4 bbox corners (already in convert_to_blender_coordinates
    space), shifted x_shift along X so multiple planes can sit side by side.
    """
    import bmesh  # type: ignore
    import bpy  # type: ignore

    remove_objects(bpy.data.objects.get(name))

    uv_coords = {"sw": (0.0, 0.0), "se": (1.0, 0.0), "ne": (1.0, 1.0), "nw": (0.0, 1.0)}

    bm = bmesh.new()
    verts = {key: bm.verts.new((pos[0] + x_shift, pos[1], 0.0)) for key, pos in corners.items()}
    bm.verts.ensure_lookup_table()
    face = bm.faces.new((verts["sw"], verts["se"], verts["ne"], verts["nw"]))

    uv_layer = bm.loops.layers.uv.new()
    vert_to_key = {v: k for k, v in verts.items()}
    for loop in face.loops:
        loop[uv_layer].uv = uv_coords[vert_to_key[loop.vert]]

    mesh = bpy.data.meshes.new(name)
    bm.to_mesh(mesh)
    bm.free()

    obj = bpy.data.objects.new(name, mesh)
    obj.location = (
        tp3d.get("xTerrainOffset", 0.0),
        tp3d.get("yTerrainOffset", 0.0),
        z_height,
    )
    collection.objects.link(obj)

    mat = bpy.data.materials.get(material_name)
    if mat is None:
        mat = bpy.data.materials.new(name=material_name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    output = nodes.new(type="ShaderNodeOutputMaterial")
    output.location = (300, 0)
    emission = nodes.new(type="ShaderNodeEmission")
    emission.location = (100, 0)
    tex = nodes.new(type="ShaderNodeTexImage")
    tex.location = (-200, 0)
    tex.image = image

    links.new(tex.outputs["Color"], emission.inputs["Color"])
    links.new(emission.outputs["Emission"], output.inputs["Surface"])

    obj.data.materials.clear()
    obj.data.materials.append(mat)

    obj.select_set(False)

    return obj


def create_satellite_plane(landcover_tiled, min_lat, max_lat, min_lon, max_lon, z_height,
                            debug_photo_tiled=None):
    """Create (or replace) a flat, unlit reference plane textured with the
    ESA WorldCover land-cover map.

    Main-thread only (bpy.data / mesh construction). landcover_tiled is a
    TiledCrop from get_cached_landcover_image() -- possibly multiple chunks,
    stitched here into one image. The plane's vertices are built from the
    same convert_to_blender_coordinates() used by terrain/OSM element
    meshes, so it lines up with the generated model regardless of
    xTerrainOffset/yTerrainOffset -- those are applied to the object's
    .location instead, matching how other element objects are positioned.

    In Blender debug mode (bpy.app.debug), if debug_photo_tiled was also
    fetched, a second plane holding the real Sentinel-2 photo is placed next
    to it (in a dedicated debug collection) so the classification can be
    checked against the source imagery.

    Outside debug mode, the plane itself is torn back down before returning
    -- it exists only to be sampled by paint_terrain_from_landcover() (which
    reads the LANDCOVER_IMAGE_NAME image datablock directly, independent of
    this object) and isn't meant to linger in the final scene.
    """
    import bpy  # type: ignore

    tp3d = bpy.context.scene.tp3d

    corners = {
        "sw": convert_to_blender_coordinates(min_lat, min_lon, 0, 0),
        "se": convert_to_blender_coordinates(min_lat, max_lon, 0, 0),
        "ne": convert_to_blender_coordinates(max_lat, max_lon, 0, 0),
        "nw": convert_to_blender_coordinates(max_lat, min_lon, 0, 0),
    }

    landcover_image = _load_stitched_image(LANDCOVER_IMAGE_NAME, landcover_tiled)
    if landcover_image is None:
        return None

    obj = _build_reference_plane(
        SATELLITE_PLANE_NAME, landcover_image, corners, x_shift=0.0,
        z_height=z_height, tp3d=tp3d, collection=bpy.context.collection,
        material_name="TP3D_Satellite",
    )

    photo_image = _load_stitched_image(PHOTO_IMAGE_NAME, debug_photo_tiled) if (
        bpy.app.debug and debug_photo_tiled) else None

    if photo_image is not None:
        width = corners["se"][0] - corners["sw"][0]
        _build_reference_plane(
            DEBUG_RAW_PLANE_NAME, photo_image, corners, x_shift=width * 1.05,
            z_height=z_height, tp3d=tp3d,
            collection=debug_collection(DEBUG_COLLECTION_NAME),
            material_name="TP3D_Satellite_DebugRaw",
        )
    else:
        # Debug mode turned off (or no photo fetched) since a prior run --
        # don't leave a stale debug plane sitting in the scene.
        remove_objects(bpy.data.objects.get(DEBUG_RAW_PLANE_NAME))

    if not bpy.app.debug:
        remove_objects(obj)
        obj = None

    return obj


def paint_terrain_from_landcover(map_obj, min_lat, max_lat, min_lon, max_lon, up_threshold=0.05):
    """Color map_obj's up-facing terrain faces by sampling the land-cover
    reference image, for PAINT elementMode.

    Same face-selection approach as terrain.py's color_map_faces_by_terrain()
    (world-space face-center test against an up-facing normal threshold),
    but instead of a Shapely contains-test against an OSM element's
    footprint, each face's world XY is mapped into the land-cover plane's
    own bbox to sample that pixel directly -- no separate polygon geometry
    needed since the image itself already is the classification.

    Faces are assigned one of the addon's existing semantic materials via
    _LANDCOVER_MATERIAL_MAP (reusing whatever color_map_faces_by_terrain
    would have used for the same category, and what the export pipeline
    maps to filament colors) rather than a new material. A face whose
    sampled pixel doesn't clearly match a known category (no-data gray, or
    off the edge of the image) is left with whatever material it already had.

    Main-thread only. Must run after create_satellite_plane() has loaded
    LANDCOVER_IMAGE_NAME (i.e. after a successful call in this same run).
    """
    import bmesh  # type: ignore
    import bpy  # type: ignore

    image = bpy.data.images.get(LANDCOVER_IMAGE_NAME)
    if image is None or map_obj is None or map_obj.type != 'MESH':
        return

    width, height = image.size
    buf = np.empty(width * height * 4, dtype=np.float32)
    image.pixels.foreach_get(buf)
    pixels = buf.reshape(height, width, 4)

    tp3d = bpy.context.scene.tp3d
    offset_x = tp3d.get("xTerrainOffset", 0.0)
    offset_y = tp3d.get("yTerrainOffset", 0.0)
    sw = convert_to_blender_coordinates(min_lat, min_lon, 0, 0)
    ne = convert_to_blender_coordinates(max_lat, max_lon, 0, 0)
    x0, y0 = sw[0] + offset_x, sw[1] + offset_y
    span_x = (ne[0] + offset_x) - x0
    span_y = (ne[1] + offset_y) - y0
    if span_x <= 0 or span_y <= 0:
        return

    class_ids = list(_LANDCOVER_PALETTE.keys())
    palette_rgb = np.array([_LANDCOVER_PALETTE[c][:3] for c in class_ids], dtype=np.float32)

    mat_index_by_class = {}
    map_mesh = map_obj.data
    for class_id, mat_name in _LANDCOVER_MATERIAL_MAP.items():
        mat = bpy.data.materials.get(mat_name)
        if mat is None:
            continue
        if mat.name not in [m.name for m in map_mesh.materials if m is not None]:
            map_mesh.materials.append(mat)
        mat_index_by_class[class_id] = map_mesh.materials.find(mat.name)

    bm = bmesh.new()
    bm.from_mesh(map_mesh)
    bm.faces.ensure_lookup_table()
    mw = map_obj.matrix_world

    up = Vector((0, 0, 1))
    painted = 0
    for f in bm.faces:
        if f.normal.normalized().dot(up) <= up_threshold:
            continue
        center = mw @ f.calc_center_median()
        u = (center.x - x0) / span_x
        v = (center.y - y0) / span_y
        if not (0.0 <= u <= 1.0 and 0.0 <= v <= 1.0):
            continue
        col = min(width - 1, int(u * width))
        row = min(height - 1, int(v * height))
        r, g, b, a = pixels[row, col]
        if a < 0.5:
            continue
        sample = np.array([r, g, b], dtype=np.float32) * 255.0
        dists = np.linalg.norm(palette_rgb - sample, axis=1)
        best = int(np.argmin(dists))
        if dists[best] > _LANDCOVER_MATCH_MAX_DIST:
            continue
        mat_index = mat_index_by_class.get(class_ids[best])
        if mat_index is None:
            continue
        f.material_index = mat_index
        painted += 1

    bm.to_mesh(map_mesh)
    bm.free()
    print(f"Painted {painted} terrain faces from land-cover image")
